# Generated by Django 6.0.4 on 2026-04-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('amazon', 'Amazon Seller'), ('ebay', 'eBay Store'), ('shopify', 'Shopify'), ('etsy', 'Etsy'), ('walmart', 'Walmart Marketplace'), ('local', 'Local / Brick & Mortar'), ('service', 'Service Business'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, help_text='Storefront or seller profile URL')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
    ]
