# Generated by Django 6.0.4 on 2026-04-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storegroup_store_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('supplier', 'Supplier / Manufacturer'), ('shipping', 'Shipping / Fulfillment'), ('platform', 'Marketplace / Platform Fee'), ('payment', 'Payment Processor'), ('advertising', 'Advertising / Marketing'), ('software', 'Software / SaaS'), ('returns', 'Returns / Refunds'), ('warehouse', 'Warehouse / Storage'), ('other', 'Other')], default='other', max_length=20)),
                ('fee_type', models.CharField(choices=[('flat', 'Flat Fee'), ('percentage', 'Percentage of Sales'), ('per_unit', 'Per Unit / Per Order'), ('variable', 'Variable')], default='variable', max_length=20)),
                ('fee_value', models.DecimalField(blank=True, decimal_places=4, help_text='Flat dollar amount or percentage (e.g. 15 for 15%)', max_digits=10, null=True)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='stores.store')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
