# Generated by Django 6.0.4 on 2026-04-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='store',
        ),
    ]
