# Generated by Django 6.0.4 on 2026-04-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_vendors_own_app'),
        ('stores', '0004_vendors_own_app'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
