# Generated by Django 6.0.4 on 2026-04-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('filing_status', models.CharField(choices=[('single', 'Single'), ('married_jointly', 'Married Filing Jointly'), ('married_separately', 'Married Filing Separately'), ('head_of_household', 'Head of Household')], default='single', max_length=20)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('state_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('qbi_eligible', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
