# Generated by Django 6.0.4 on 2026-04-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxprofile',
            name='business_type',
            field=models.CharField(choices=[('sole_prop', 'Sole Proprietor'), ('llc_single', 'Single-Member LLC'), ('llc_multi', 'Multi-Member LLC'), ('s_corp', 'S-Corporation')], default='sole_prop', max_length=20),
        ),
        migrations.AddField(
            model_name='taxprofile',
            name='owner_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
