# Generated by Django 6.0.4 on 2026-04-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_transaction_store'),
        ('stores', '0003_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='stores.vendor'),
        ),
    ]
