# Generated by Django 6.0.4 on 2026-04-16 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_transaction_vendor'),
        ('vendors', '0001_vendors_own_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='vendors.vendor'),
        ),
    ]
