# Generated by Django 6.0.4 on 2026-04-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_vendors_own_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
